FROM node:20-slim

WORKDIR /app

COPY package*.json /app/

RUN npm install --no-audit --no-fund

COPY tsconfig.json /app/tsconfig.json
COPY tsconfig.node.json /app/tsconfig.node.json
COPY vite.config.mts /app/vite.config.mts
COPY index.html /app/index.html
COPY public /app/public
COPY src /app/src

EXPOSE 5173

CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0", "--port", "5173"]
